# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:02
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastdays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 6, 2, 24, 218110)),
            preserve_default=False,
        ),
    ]
