# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastdays', '0002_auto_20170826_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
